baseURL = "https://hiskia.app/"
title = "Hiskia ʕ•ᴥ•ʔ"
author = "Hiskia"
copyright = "Copyright © 2026, Hiskia."
languageCode = "en-US"
enableRobotsTXT = true
enableGitInfo = true

disableKinds = ["taxonomy", "term", "RSS", "section"]
ignoreErrors = ["error-disable-taxonomy"]

[minify]
minifyOutput = true

[params]
description = "Software engineer working across web engineering, DevOps, and infrastructure."
favicon = "images/favicon.svg"
images = ["images/share.svg"]
title = "Hiskia ʕ•ᴥ•ʔ"
linkedinURL = "https://linkedin.com/in/h23a"
githubURL = "https://github.com/h23a"
email = "hi@hiskia.app"
resumeURL = "https://drive.google.com/file/d/1csotvjX6nZ5xVFN4V-WbuJPvJSIa1O39/view"
